// frontend/src/lib/components/molecules/SelectField.svelte
<script lang="ts">
    import type { Option } from "$lib/core/options";
    import InputTitle from "../atoms/InputTitle.svelte";

    type Props = {
        readonly title: string;
        readonly name: string;
        readonly options: readonly Option<string>[];
        readonly value: string;
        readonly onChange: (newValue: string) => void;
    };

    const { title, name, options, value, onChange }: Props = $props();
</script>

<style>
    div {
        display: flex;
    }
</style>

<div>
    <InputTitle>{title}</InputTitle>
    <SelectInput
        {name}
        {options}
        {value}
        {onChange}
    />
</div>

// frontend/src/comp/molecules/SelectField.tsx
import type { JSX } from "react";
import type { Options } from "@/lib/options";
import { InputTitle } from "../atoms/InputTitle";
import { SelectInput } from "../atoms/SelectInput";

type Props<T extends string | number> = {
    readonly title: string;
    readonly name: string;
    readonly options: Options<T>;
    readonly value: T;
    readonly onChange: (newValue: T) => void;
};

export function SelectField<T extends string | number>({
    title,
    name,
    options,
    value,
    onChange,
}: Props<T>): JSX.Element {
    return (
        <div className="flex-auto">
            <InputTitle>{title}</InputTitle>
            <SelectInput
                name={name}
                options={options}
                value={value}
                onChange={onChange}
            />
        </div>
    );
}
