// frontend/src/feat/Tuning/Form.tsx
import type { ScaleName } from "@/core/scale";
import type { InstrumentName } from "@/core/instrument";
import type { Note } from "@/core/note";
import { instrument, instrumentBusiness } from "@/core/instrument";
import { noteBusiness } from "@/core/note";
import { scaleBusiness } from "@/core/scale";
import { SelectField } from "@/comp/molecules/SelectField";
import { NumberField } from "@/comp/molecules/NumberField";

const instrumentOptions = instrumentBusiness.getOptions();
const scaleKindOptions = scaleBusiness.getOptions();
const notesOptions = noteBusiness.getOptions();

type Props = {
    readonly selectedInstrument: InstrumentName;
    readonly setInstrument: (selectedInstrument: InstrumentName) => void;
    readonly scaleNote: Note["number"];
    readonly setScale: (scaleNote: Note["number"]) => void;
    readonly fretNumber: number;
    readonly setFretNumber: (fretNumber: number) => void;
    readonly numberOfStrings: number;
    readonly setStringNumber: (numberOfStrings: number) => void;
    readonly scaleKind: ScaleName;
    readonly setScaleKind: (scaleKind: ScaleName) => void;
    readonly tuningKind: string;
    readonly setTuningKind: (tuningKind: string) => void;
};

export function TuningForm({
    selectedInstrument,
    setInstrument,
    scaleNote,
    setScale,
    fretNumber,
    setFretNumber,
    numberOfStrings,
    setStringNumber,
    scaleKind,
    setScaleKind,
    tuningKind,
    setTuningKind,
}: Props): JSX.Element {
    const tuningKinds = instrumentBusiness.getTuneOptions({
        selectedInstrument,
        numberOfStrings: numberOfStrings as any,
    });

    return (
        <div className="w-48 bg-gray-200 flex flex-col items-center">
            <div>
                <SelectField
                    title="Instrument"
                    name="instrument"
                    options={instrumentOptions}
                    value={selectedInstrument}
                    onChange={(newInstrument: "guitar" | "bass") => {
                        setInstrument(newInstrument);
                        setStringNumber(
                            instrument[newInstrument].numberOfStrings.default,
                        );
                        setTuningKind("standard");
                    }}
                />
                <NumberField
                    title="Frets"
                    min={11}
                    max={24}
                    value={fretNumber}
                    onChange={setFretNumber}
                />
                <NumberField
                    title="Strings"
                    min={instrument[selectedInstrument].numberOfStrings.min}
                    max={instrument[selectedInstrument].numberOfStrings.max}
                    value={numberOfStrings}
                    onChange={(newStringNumber) => {
                        setStringNumber(newStringNumber);
                        setTuningKind("standard");
                    }}
                />
                <SelectField
                    name="scaleKind"
                    title="Scale"
                    options={scaleKindOptions}
                    value={scaleKind}
                    onChange={setScaleKind}
                />
                <SelectField
                    title="Tuning"
                    name="tuningKind"
                    options={tuningKinds}
                    value={tuningKind}
                    onChange={setTuningKind}
                />
                <SelectField
                    title="Key"
                    name="key"
                    options={notesOptions}
                    value={scaleNote}
                    onChange={setScale}
                />
            </div>
        </div>
    );
}

// frontend/src/lib/features/Tuning/Form.svelte
<script lang="ts">
    import type { ScaleKind } from "@/core/scale";
    import type { Instrument, Tuning } from "@/core/instrument";
    import type { Note } from "@/core/note";
    import {
        getMaxNumberOfStrings,
        getMinNumberOfStrings,
        getTuningOptions,
        instrumentOptions,
        noteOptions,
        scaleKindOptions,
    } from "@/lib/options";
    import { SelectField } from "@/comp/molecules/SelectField";
    import { NumberField } from "@/comp/molecules/NumberField";

    type Props = {
        readonly instrument: Instrument;
        readonly root: Note;
        readonly numberOfFrets: number;
        readonly numberOfStrings: number;
        readonly scaleKind: ScaleKind;
        readonly tuning: Tuning;
        readonly onChangeInstrument: (instrument: Instrument) => void;
        readonly onChangeRoot: (root: Note) => void;
        readonly onChangeNumberOfFrets: (numberOfFrets: number) => void;
        readonly onChangeNumberOfStrings: (numberOfStrings: number) => void;
        readonly onChangeScaleKind: (scaleKind: ScaleKind) => void;
        readonly onChangeTuning: (tuning: Tuning) => void;
    };
    const tuningOptions = getTuningOptions(
        instrument,
        numberOfStrings,
    );
</script>

<div className="w-48 bg-gray-200 flex flex-col items-center">
    <div>
        <SelectField
            title="Instrument"
            name="instrument"
            options={instrumentOptions}
            value={instrument}
            onChange={onChangeInstrument}
        />
        <NumberField
            title="Frets"
            min={11}
            max={24}
            value={numberOfFrets}
            onChange={onChangeNumberOfFrets}
        />
        <NumberField
            title="Strings"
            min={getMinNumberOfStrings(instrument)}
            max={getMaxNumberOfStrings(instrument)}
            value={numberOfStrings}
            onChange={onChangeNumberOfStrings}
        />
        <SelectField
            name="scaleKind"
            title="Scale"
            options={scaleKindOptions}
            value={scaleKind}
            onChange={onChangeScaleKind}
        />
        <SelectField
            title="Tuning"
            name="tuning"
            options={tuningOptions}
            value={tuning}
            onChange={onChangeTuning}
        />
        <SelectField
            title="Key"
            name="key"
            options={noteOptions}
            value={root}
            onChange={onChangeRoot}
        />
    </div>
</div>
