// frontend/src/lib/components/molecules/NumberField.svelte
<script lang="ts">
    import InputTitle from "../atoms/InputTitle.svelte";
    import NumberInput from "../atoms/NumberInput.svelte";

    type Props = {
        readonly title: string;
        readonly min: number;
        readonly max: number;
        readonly value: number;
        readonly onChange: (value: number) => void;
    };

    const { title, min, max, value, onChange }: Props = $props();
</script>

<style>
    div {
        display: flex;
    }
</style>

<div>
    <InputTitle>{title}</InputTitle>
    <NumberInput
        {min}
        {max}
        {value}
        {onChange}
    />
</div>

// frontend/src/components/molecules/NumberField.tsx
import type { JSX } from "react";
import { InputTitle } from "../atoms/InputTitle";
import { NumberInput } from "../atoms/NumberInput";

type Props<T extends number> = {
    readonly title: string;
    readonly min: number;
    readonly max: number;
    readonly value: T;
    readonly onChange: (value: T) => void;
};

export function NumberField<T extends number>({
    value,
    min,
    max,
    onChange,
    title,
}: Props<T>): JSX.Element {
    return (
        <div className="flex-auto">
            <InputTitle>{title}</InputTitle>
            <NumberInput
                min={min}
                max={max}
                value={value}
                onChange={onChange}
            />
        </div>
    );
}
