// src/components/atoms/NumberInput.tsx
type props = {
    value: number;
    min: number;
    max: number;
    onChange: (value: number) => void;
};

export function NumberInput({ value, min, max, onChange }: props) {
    function handleOnChange(newValue: string) {
        const maybeValue = Number(newValue);
        if (!maybeValue) return;
        if (maybeValue > max) return;
        if (maybeValue < min) return;
        onChange(maybeValue);
    }

    return (
        <input
            type='number'
            className='w-28 h-14 px-2 py-1 outline-none border border-transparent focus:border-gray-300 rounded'
            min={min}
            max={max}
            onChange={e => handleOnChange(e.target.value)}
            value={value}
        />
    );
}

// frontend/src/lib/components/atoms/NumberInput.svelte
<script lang="ts">
    type Props = {
        readonly min: number;
        readonly max: number;
        readonly value: number;
        readonly onChange: (newValue: number) => void;
    };

    const {
        min,
        max,
        value,
        onChange,
    }: Props = $props();

    function handleOnChange(value: string) {
        if (!value) return;
        const newValue = Number(value);
        if (newValue > max || newValue < min) {
            return;
        }
        onChange(newValue);
    }
</script>

<input
    type="number"
    oninput={(e) => handleOnChange(e.currentTarget.value)}
    {min}
    {max}
    {value}
/>
