// frontend/src/lib/components/molecules/NumberField.svelte
<script lang="ts">
    import InputTitle from "../atoms/InputTitle.svelte";
    import NumberInput from "../atoms/NumberInput.svelte";

    type Props = {
        readonly title: string;
        readonly min: number;
        readonly max: number;
        readonly value: number;
        readonly onChange: (value: number) => void;
    };

    const { title, min, max, value, onChange }: Props = $props();
</script>

<style>
    div {
        display: flex;
    }
</style>

<div>
    <InputTitle>{title}</InputTitle>
    <NumberInput
        {min}
        {max}
        {value}
        {onChange}
    />
</div>

// src/components/molecules/NumberField.tsx
import { InputTitle } from '../atoms/InputTitle';
import { NumberInput } from '../atoms/NumberInput';

type props = {
    value: number;
    min: number;
    max: number;
    onChange: (value: number) => void;
    title: string;
};

export function NumberField({ value, min, max, onChange, title }: props) {
    return (
        <div className='flex-auto'>
            <InputTitle>{title}</InputTitle>
            <NumberInput
                min={min}
                max={max}
                value={value}
                onChange={onChange}
            />
        </div>
    );
}
